WIP: Swift 4 - RxSwift 4.0 - GoogleMaps 2.5.0
RxSwiftCommunity/RxGoogleMaps pull request #9
Opened 2017-10-28 16:37 UTC by GabrielAraujo

This Pull request is to adjust this framework to the same layout as other RxSwiftCommunity and also to update to the latest Swift 4, RxSwift 4.0 and Google Maps 2.5.0

2017-11-02 15:04 UTC, GabrielAraujo commented
I've changed the entire project structure. Due to the new way that DelegateProxy needs to be created we could no longer use some wrapper around the GMSMapView file as was with RxGMSMapView.

Other important thing to take note is that GoogleMaps still supports ios7 and due to that we can't include it into our podspec as a dependency otherwise when you try to install it will complain about static binaries.

2017-11-02 15:05 UTC, GabrielAraujo commented
@freak4pc could you please take a look at the changes and accept the PR? We should keep the old the current project in a Version 2.3 branch.

2017-11-02 15:10 UTC, freak4pc requested changes
Some superficial styling notes. I'll clone the project in a bit to test.

2017-11-02 15:10 UTC, freak4pc commented on Example/RxGoogleMaps/GMSCircle+Rx.swift
> +            }.asObserver()
Can we make sure all closing brackets are in line with the returns ?

2017-11-02 15:10 UTC, freak4pc commented on Sources/GMSMapViewDelegateProxy.swift
> +        return self.didHandleTapOverlay(overlay)!
Can we avoid the force unwrap here?

2017-11-02 15:10 UTC, freak4pc commented on Example/RxGoogleMaps/GMSMapViewDelegateProxy.swift
> +        return self.didHandleTapOverlay(overlay)!
Can we please avoid the force unwrap here as well?

2017-11-02 15:10 UTC, freak4pc commented on Sources/GMSMapViewDelegateProxy.swift
> +// Referred from RxCococa.swift because it's not public
Can we just get rid of this comment and add a 
`// - MARK: Internal Helpers` or something of sorts

2017-11-02 15:29 UTC, GabrielAraujo commented
@freak4pc made the corrections, I think I'm going to remove cocoapods and carthage support. We do not use them as we have to manually add the files from Sources folder into our project.
What do you think?

2017-11-02 15:32 UTC, freak4pc commented
@GabrielAraujo Not sure I understand you? CocoaPods and Carthage support for repos is pretty required as those are the two primary methods of usage today :)

2017-11-02 15:43 UTC, GabrielAraujo commented
@freak4pc the problem is that GoogleMaps is not a Dynamic framework and will continue like that until Google drops support for iOS7. Because of this we can't add GoogleMaps as a dependency on cocoapods. 

 This project currently use a wrapper for GoogleMaps and a bridge file to make it work but we can no longer create a wrapper around GoogleMaps as now at the DelegateProxy class you have to identify the class and the delegate. In this case `DelegateProxy<GMSMapView, GMSMapViewDelegate>`.

So now that the changes I have made have direct access to GoogleMaps we can't use cocoapods nor carthage as the project will always break complaining about missing GoogleMaps dependency.

2017-11-02 16:51 UTC, freak4pc commented
That's not a good compromise to be honest. I prefer serving this as a Cocoapods/Carthage and instruct users to manually add the Google Maps dependency if there's no other choice, but completely getting rid of dependency managers is a no-go here and it's a regression from the current state of this library where you could just install and go

2017-11-02 16:57 UTC, freak4pc commented
Also seems CocoaPods is supported? @GabrielAraujo 

<img width="906" alt="030e90d7-3526-4a32-8fc7-445d05e1dd1f" src="https://user-images.githubusercontent.com/605076/32339196-b4b3d974-bfff-11e7-8f03-30a75a82895e.png">

2017-11-02 23:59 UTC, GabrielAraujo commented
@freak4pc them I think the best way would keep the cocoapods installation and put a note that user must delete the files from the pod project at every pod install or update. Do you know if there is a command for automatically moving the files into the main project and deleting from RxGoogleMaps?

Regarding your second comment. You can  install directly from your pod, what you can't is to add it as a dependency in the podspec file.

You can have more details here
https://github.com/CocoaPods/CocoaPods/issues/5624

2017-11-03 01:22 UTC, GabrielAraujo commented
@freak4pc after looking into some issues in the Cocoapods repo I discovered that they had added support for static frameworks recently. So I just had to install the latest not yet release version of cocoapods by doing `sudo gem install cocoapods --pre`

I think now everything is good to go!

2017-11-03 08:21 UTC, freak4pc commented on RxGoogleMaps.podspec
> +  s.static_framework = true
Neat !

2017-11-03 08:25 UTC, freak4pc commented on README.md
> +    .disposed(by: disposeBag)
Except for the syntactical fixes here, are there any updates to the examples themselves that stem from your massive refactor here? Or the code should be relatively similar? Perhaps an update to the README is in order?

2017-11-03 08:43 UTC, freak4pc commented
Hey @GabrielAraujo, There are still a few more problems that need resolution here. 

- Your Example project has a "Copy Bundle Resources" of `key.plist` but the file doesn't exist, meaning the project doesn't compile past this point. It also means I can't test the project as it requires some key. Perhaps would be good to have a demo account there with some key so it works out of the box.
<img width="279" alt="515062a6-fb56-4f44-84c7-680c379c9afd" src="https://user-images.githubusercontent.com/605076/32365625-30a4c6f0-c083-11e7-8c6b-8ee4409605f4.png">

- Please update the README with some code examples to reflect the new code additions (unless you think there's nothing worth adding). Your example project seems to have MANY examples - choose the 2-3 most useful ones and put them in the README.

- Please update the README to add the following under the cocoapods Installation
```
  *Note:* Due to the fact Google Maps is delivered as a static library, you must have CocoaPods 1.4.0 installed to install this library (`gem install cocoapods --pre`)
```

Until those 3 are resolved (or the first one specifically) I have no way to functionally test this :( Let me know when you're ready. No rush!

2017-11-03 23:39 UTC, GabrielAraujo commented
@freak4pc did the changes you asked! I just can't add the key as it would require a google account but I have added a little tutorial on how to setup the example project. =)

2017-11-04 11:14 UTC, freak4pc commented
Hey @GabrielAraujo 
Great changes to the README. 

I went with a different approach to make the project "Compile" easily
1. I removed the plist all together,
2. I added a `YOUR-API-KEY` placeholder in AppDelegate
3. Added relevant instructions in AppDelegate and README

I also went through the code a bit deeper now and there seems to be a couple of issues: 

1. The ViewController has a bunch of commented code, If it's commented out, just delete it - make sure the file is clean with only the needed parts as part of it to reduce confusion.

2. `GMSMapViewDelegateProxy` seems to have a bunch of Closure references? This is a bit odd to me. You have a `mapView.rx.handleTapMarker = { } ` where you would expect this would be a `mapView.rx.tappedMark.bind(to: something)`. The former isn't very Rx-y, it's just a regular callback. I'm not sure why you chose this strategy, could you elaborate?

2017-11-04 14:17 UTC, GabrielAraujo commented
@freak4pc 
1 - I removed the comments but not the code, I think that those are great examples.

2 - This was already being used previously, I tried to make Rx-y but all those functions that are using callbacks but crashed at runtime. The error was something like this method doesn't belong to this class. If you look at GMSMapViewDelegate you can see them there but you can't reference them as like the others that are in the Rx-y way. I tried to find a solution but we can't do a deeper analysis on the GoogleMaps sdk =(..

2017-11-04 15:58 UTC, freak4pc approved these changes

2017-11-04 15:59 UTC, freak4pc commented
Looks good to me. Let's merge this and keep improving these issues later on.

2017-11-04 15:59 UTC, merged

2017-11-04 16:23 UTC, GabrielAraujo commented
Thanks @freak4pc..

We also need to update the cocoa pods page. Do you know how can we do that?

2017-11-04 21:12 UTC, freak4pc commented
@inkyfox Can you please push a new Podspec here? If you're available to do so :)